name: Release Jar on Main Push

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v0.9.3 등 태그 푸시 시 실행

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build JAR with Gradle
        run: ./gradlew bootJar

      - name: Upload JAR to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/duckstar.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}